-- Categories Seed Script

INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Masks', 'masks-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety Wear & Equipment', 'safety-wear-and-equipment', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Masks', 'masks-safety-wear-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-wear-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Workwear & PPE', 'workwear-and-ppe', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gloves', 'gloves-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Protective Wear', 'protective-wear-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Workwear', 'workwear-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Medical', 'medical', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Protective Wear', 'protective-wear-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('First Aid', 'first-aid-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety Harnesses', 'safety-harnesses-safety-wear-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-wear-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Eye Protection', 'eye-protection-safety-wear-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-wear-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Head Protection', 'head-protection-safety-wear-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-wear-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety & Equipment', 'safety-and-equipment-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Ear Protection', 'ear-protection-safety-wear-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-wear-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Masks', 'masks-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Disposables', 'disposables-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety Equipment', 'safety-equipment-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe-safety-wear-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-wear-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Medical', 'medical-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Foot protection', 'foot-protection-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Workwear', 'workwear-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Roadworks and safety', 'roadworks-and-safety', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe-roadworks-and-safety', (SELECT id FROM categories WHERE slug = 'roadworks-and-safety')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Security', 'security', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Workwear', 'workwear-security', (SELECT id FROM categories WHERE slug = 'security')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety Shoes', 'safety-shoes-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Shoes', 'shoes-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Automotive', 'automotive', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Boots', 'boots-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Hospitality', 'hospitality', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe-automotive', (SELECT id FROM categories WHERE slug = 'automotive')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe-hospitality', (SELECT id FROM categories WHERE slug = 'hospitality')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gum boots', 'gum-boots-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Uncategorized', 'uncategorized', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety Boots', 'safety-boots-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Fire Safety and Protection', 'fire-safety-and-protection', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gloves', 'gloves-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety & Equipment', 'safety-and-equipment', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety', 'safety-safety-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Outdoor', 'outdoor', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Camping', 'camping-outdoor', (SELECT id FROM categories WHERE slug = 'outdoor')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety Accessories', 'safety-accessories-safety-wear-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-wear-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Security Wear', 'security-wear-security', (SELECT id FROM categories WHERE slug = 'security')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Security Footwear', 'security-footwear-security', (SELECT id FROM categories WHERE slug = 'security')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Security Defence', 'security-defence-security', (SELECT id FROM categories WHERE slug = 'security')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Lockout Devices', 'lockout-devices', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Industrial Safety', 'industrial-safety-lockout-devices', (SELECT id FROM categories WHERE slug = 'lockout-devices')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Emergency Kits', 'emergency-kits-fire-safety-and-protection', (SELECT id FROM categories WHERE slug = 'fire-safety-and-protection')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Traffic Safety', 'traffic-safety-roadworks-and-safety', (SELECT id FROM categories WHERE slug = 'roadworks-and-safety')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Signals', 'signals-roadworks-and-safety', (SELECT id FROM categories WHERE slug = 'roadworks-and-safety')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning', 'cleaning', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Hand Cleaner', 'hand-cleaner-cleaning', (SELECT id FROM categories WHERE slug = 'cleaning')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning Liquid', 'cleaning-liquid-cleaning', (SELECT id FROM categories WHERE slug = 'cleaning')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Rags', 'rags-cleaning', (SELECT id FROM categories WHERE slug = 'cleaning')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning Safety', 'cleaning-safety-cleaning', (SELECT id FROM categories WHERE slug = 'cleaning')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Mops', 'mops-cleaning', (SELECT id FROM categories WHERE slug = 'cleaning')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Brooms', 'brooms-cleaning', (SELECT id FROM categories WHERE slug = 'cleaning')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gloves', 'gloves-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Disposables', 'disposables', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Medical', 'medical-disposables', (SELECT id FROM categories WHERE slug = 'disposables')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('PPE', 'ppe-disposables', (SELECT id FROM categories WHERE slug = 'disposables')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gloves', 'gloves-hospitality', (SELECT id FROM categories WHERE slug = 'hospitality')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gumboots', 'gumboots-workwear-and-ppe', (SELECT id FROM categories WHERE slug = 'workwear-and-ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Security Accessories', 'security-accessories-security', (SELECT id FROM categories WHERE slug = 'security')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning & Equipment', 'cleaning-and-equipment', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning Supplies', 'cleaning-supplies-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning equipment', 'cleaning-equipment-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Barriers', 'barriers-roadworks-and-safety', (SELECT id FROM categories WHERE slug = 'roadworks-and-safety')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Chemicals', 'chemicals-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Household', 'household', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Chemicals', 'chemicals-household', (SELECT id FROM categories WHERE slug = 'household')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning & Equipment', 'cleaning-and-equipment-household', (SELECT id FROM categories WHERE slug = 'household')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Industrial Cleaning', 'industrial-cleaning-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning & Equipment', 'cleaning-and-equipment-hospitality', (SELECT id FROM categories WHERE slug = 'hospitality')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Automotive', 'automotive-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Chemicals', 'chemicals-automotive', (SELECT id FROM categories WHERE slug = 'automotive')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Household', 'household-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Hand Cleaner Household Industrial Clearner', 'hand-cleaner-household-industrial-clearner-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Hand Soap', 'hand-soap-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Paper Products', 'paper-products', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Industrial Cleaning', 'industrial-cleaning-paper-products', (SELECT id FROM categories WHERE slug = 'paper-products')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cloths & Wipes', 'cloths-and-wipes-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Rags', 'rags-automotive', (SELECT id FROM categories WHERE slug = 'automotive')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Speed bumps', 'speed-bumps-roadworks-and-safety', (SELECT id FROM categories WHERE slug = 'roadworks-and-safety')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Catering', 'catering-paper-products', (SELECT id FROM categories WHERE slug = 'paper-products')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Catering', 'catering-hospitality', (SELECT id FROM categories WHERE slug = 'hospitality')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Catering', 'catering-household', (SELECT id FROM categories WHERE slug = 'household')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Packaging', 'packaging', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Disposable bags', 'disposable-bags-packaging', (SELECT id FROM categories WHERE slug = 'packaging')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Storage & Bins', 'storage-and-bins', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Bins', 'bins-storage-and-bins', (SELECT id FROM categories WHERE slug = 'storage-and-bins')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Bins', 'bins-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Storage & Bins', 'storage-and-bins-hospitality', (SELECT id FROM categories WHERE slug = 'hospitality')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Storage & Bins', 'storage-and-bins-household', (SELECT id FROM categories WHERE slug = 'household')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Shade', 'shade-outdoor', (SELECT id FROM categories WHERE slug = 'outdoor')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Tool Boxes', 'tool-boxes-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Storage', 'storage-storage-and-bins', (SELECT id FROM categories WHERE slug = 'storage-and-bins')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cooler Boxes', 'cooler-boxes-outdoor', (SELECT id FROM categories WHERE slug = 'outdoor')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Medical', 'medical-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Lab Coats', 'lab-coats-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Lab Coats', 'lab-coats-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning & Equipment', 'cleaning-and-equipment-disposables', (SELECT id FROM categories WHERE slug = 'disposables')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Kids Products', 'kids-products', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Hygiene Protection', 'hygiene-protection', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Nappies', 'nappies-hygiene-protection', (SELECT id FROM categories WHERE slug = 'hygiene-protection')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Sanitary Pads', 'sanitary-pads-hygiene-protection', (SELECT id FROM categories WHERE slug = 'hygiene-protection')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cleaning Accessories', 'cleaning-accessories-automotive', (SELECT id FROM categories WHERE slug = 'automotive')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety & Equipment', 'safety-and-equipment-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cloths & Wipes', 'cloths-and-wipes-automotive', (SELECT id FROM categories WHERE slug = 'automotive')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Dispensers', 'dispensers-cleaning-and-equipment', (SELECT id FROM categories WHERE slug = 'cleaning-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('First Aid', 'first-aid-safety-and-equipment', (SELECT id FROM categories WHERE slug = 'safety-and-equipment')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Cornices', 'cornices-household', (SELECT id FROM categories WHERE slug = 'household')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Household', 'household-paper-products', (SELECT id FROM categories WHERE slug = 'paper-products')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gowns', 'gowns-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gowns', 'gowns-disposables', (SELECT id FROM categories WHERE slug = 'disposables')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gowns', 'gowns-ppe', (SELECT id FROM categories WHERE slug = 'ppe')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Workwear', 'workwear-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Safety & Workwear', 'safety-and-workwear-hospitality', (SELECT id FROM categories WHERE slug = 'hospitality')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Catering', 'catering-kids-products', (SELECT id FROM categories WHERE slug = 'kids-products')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Hospitality', 'hospitality-kids-products', (SELECT id FROM categories WHERE slug = 'kids-products')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Household', 'household-kids-products', (SELECT id FROM categories WHERE slug = 'kids-products')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Toys', 'toys-kids-products', (SELECT id FROM categories WHERE slug = 'kids-products')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Bathroom Products', 'bathroom-products-paper-products', (SELECT id FROM categories WHERE slug = 'paper-products')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Masks', 'masks-disposables', (SELECT id FROM categories WHERE slug = 'disposables')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Masks', 'masks-hospitality', (SELECT id FROM categories WHERE slug = 'hospitality')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Gloves', 'gloves-disposables', (SELECT id FROM categories WHERE slug = 'disposables')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Waste Bins', 'waste-bins-medical', (SELECT id FROM categories WHERE slug = 'medical')) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Food Products', 'food-products', NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id) VALUES ('Catering', 'catering-food-products', (SELECT id FROM categories WHERE slug = 'food-products')) ON CONFLICT (slug) DO NOTHING;