-- SQL 1: Insert Categories (IDs as UUIDs, parent_id initially NULL)
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-equipment-automotive-cleaning-equipment', 'Automotive', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'automotive-2', 'Automotive', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'roadworks-barriers', 'Barriers', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'bathroom-products', 'Bathroom Products', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-equipment-bins', 'Bins', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'storage-bins-bins', 'Bins', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'boots', 'Boots', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'brooms', 'Brooms', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'camping-outdoor', 'Camping', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'household-catering', 'Catering', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'catering-food-products', 'Catering', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'kids-products-catering', 'Catering', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'catering', 'Catering', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hospitality-hospitality', 'Catering', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'automotive-chemicals', 'Chemicals', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-equipment-chemicals', 'Chemicals', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'household-chemicals', 'Chemicals', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning', 'Cleaning', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hospitality-cleaning-equipment', 'Cleaning & Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-equipment', 'Cleaning & Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'household-cleaning-equipment', 'Cleaning & Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposables-cleaning-equipment', 'Cleaning & Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'automotive-cleaning-accessories', 'Cleaning Accessories', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-equipment-equipment', 'Cleaning equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-liquid', 'Cleaning Liquid', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-safety', 'Cleaning Safety', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-supplies-cleaning-equipment', 'Cleaning Supplies', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'automotive-cloths-wipes', 'Cloths & Wipes', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-equipment-cloths-wipes', 'Cloths & Wipes', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cooler-boxes-outdoor', 'Cooler Boxes', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cornices', 'Cornices', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-equipment-dispensers', 'Dispensers', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposable-bags', 'Disposable bags', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposables', 'Disposables', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposables-2', 'Disposables', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ear-protection-safety-wear-equipment', 'Ear Protection', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'emergency-kits', 'Emergency Kits', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'eye-protection', 'Eye Protection', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'fire-safety-and-protection', 'Fire Safety and Protection', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-equipment-first-aid', 'First Aid', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'first-aid', 'First Aid', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'food-products', 'Food Products', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'foot-protection-workwear-ppe', 'Foot protection', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe-gloves-ppe', 'Gloves', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'gloves-medical', 'Gloves', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hospitality-gloves', 'Gloves', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'gloves', 'Gloves', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposables-gloves', 'Gloves', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'medical-gowns', 'Gowns', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposables-gowns', 'Gowns', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe-gowns', 'Gowns', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'gum-boots-workwear-ppe', 'Gum boots', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'gumboots', 'Gumboots', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hand-cleaner', 'Hand Cleaner', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hand-cleaner-household-industrial-clearner-cleaning-equipment', 'Hand Cleaner Household Industrial Clearner', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hand-soap', 'Hand Soap', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'head-protection', 'Head Protection', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'kids-products-hospitality', 'Hospitality', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hospitality', 'Hospitality', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'household', 'Household', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'household-cleaning-equipment-2', 'Household', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'kids-products-household', 'Household', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'household-2', 'Household', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hygiene-protection', 'Hygiene Protection', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'cleaning-equipment-industrial-cleaning', 'Industrial Cleaning', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'industrial-cleaning-paper-products', 'Industrial Cleaning', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'industrial-safety', 'Industrial Safety', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'kids-products', 'Kids Products', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe-lab-coats', 'Lab Coats', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'medical-lab-coats', 'Lab Coats', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'lockout-devices', 'Lockout Devices', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'masks', 'Masks', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposables-masks', 'Masks', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hospitality-masks', 'Masks', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe-masks', 'Masks', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-wear-equipment-masks', 'Masks', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposable-medical', 'Medical', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'medical-medical', 'Medical', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'medical-ppe-2', 'Medical', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'medical', 'Medical', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'mops', 'Mops', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'nappies', 'Nappies', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'outdoor', 'Outdoor', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'packaging', 'Packaging', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'paper-products', 'Paper Products', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe-medical-2', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-wear-equipment-ppe', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe-ppe', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'workwear-ppe-ppe', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe-ppe-2', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'disposables-ppe', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'automotive-ppe', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'roadworks-safety-ppe', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hospitality-ppe', 'PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'protective-wear', 'Protective Wear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'protective-wear-medical', 'Protective Wear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'automotive-rags', 'Rags', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'rags', 'Rags', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'roadworks-and-safety', 'Roadworks and safety', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety', 'Safety', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'ppe-safety-equipment', 'Safety & Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-equipment-medical', 'Safety & Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-equipment', 'Safety & Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hospitality-safety-workwear', 'Safety & Workwear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-accessories', 'Safety Accessories', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-boots-workwear-ppe', 'Safety Boots', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-equipment-workwear-ppe', 'Safety Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-harnesses-safety-wear-equipment', 'Safety Harnesses', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-harnesses', 'Safety Harnesses', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-shoes-workwear-ppe', 'Safety Shoes', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'safety-wear-equipment', 'Safety Wear & Equipment', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'sanitary-pads', 'Sanitary Pads', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'security', 'Security', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'security-accessories', 'Security Accessories', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'security-defence', 'Security Defence', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'security-footwear', 'Security Footwear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'security-wear', 'Security Wear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'shade', 'Shade', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'shoes', 'Shoes', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'roadworks-signals', 'Signals', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'roadworks-speed-bumps', 'Speed bumps', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'storage-bins-storage', 'Storage', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'storage-bins', 'Storage & Bins', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'household-storage-bins', 'Storage & Bins', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'hospitality-storage-bins', 'Storage & Bins', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'household-storage-bins-household-2', 'Storage & Bins', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'tool-boxes', 'Tool Boxes', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'kids-products-toys', 'Toys', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'roadworks-traffic-safety', 'Traffic Safety', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'uncategorized', 'Uncategorized', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'waste-bins', 'Waste Bins', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'workwear', 'Workwear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'workwear-security', 'Workwear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'workwear-ppe-2', 'Workwear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'workwear-medical', 'Workwear', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (id, slug, name, description, parent_id) VALUES (gen_random_uuid(), 'workwear-ppe', 'Workwear & PPE', NULL, NULL) ON CONFLICT (slug) DO NOTHING;
