-- SQL Insert for Brands Table
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'UNDEFINED', 'UNDEFINED', NULL, '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), '3D', '3d', NULL, '/brands/car-wash-auto-detailing-cadillac-escalade-3d-products-car-300x300.jpg') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Bathroom Products', 'bathroom-products', NULL, '/brands/6-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Catering', 'catering', NULL, '/brands/2-1-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Cleaning Supplies', 'cleaning-supplies', NULL, '/brands/3-2-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Cornices', 'cornices', NULL, '/brands/4-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Dromex', 'dromex', NULL, '/brands/dromex-logo-300x100.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Duraglove', 'duraglove', NULL, '/brands/DuraGlove_logo-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Durawipe', 'durawipe', NULL, '/brands/5-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Everest Safety', 'everest-safety', NULL, '/brands/Everest_Safety_Logo-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Evergreen', 'evergreen', NULL, '/brands/Evergreen-logo-300x59.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'First Aid', 'first-aid', NULL, '/brands/7-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Golden Hands', 'golden-hands', NULL, '/brands/Golden-Hands-300x112.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Household', 'household', NULL, '/brands/8-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Hygiene Protection', 'hygiene-protection', NULL, '/brands/9-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Industrial Cleaning', 'industrial-cleaning', NULL, '/brands/12-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Kiddies Corner', 'kiddies-corner', NULL, '/brands/10-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Masks', 'masks', NULL, '/brands/16-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Medical Disposal', 'medical-disposal', NULL, '/brands/11-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Nomex', 'nomex', NULL, '/brands/dupont-nomex-logo-png_seeklogo-388698-300x300.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Pinnacle', 'pinnacle', NULL, '/brands/Black-Logo-WEBP-300x135.webp') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Pioneer', 'pioneer', NULL, '/brands/Prioneer-Safety-300x32.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'PPE', 'ppe', NULL, '/brands/14-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Pride', 'pride', NULL, '/brands/UVH-site-image.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Proflex', 'proflex', NULL, '/brands/UVH-site-image.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Road Equipment', 'road-equipment', NULL, '/brands/13-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Safety', 'safety', NULL, '/brands/15-300x180.png') ON CONFLICT (slug) DO NOTHING;
INSERT INTO brands (id, name, slug, description, logo_url) VALUES (gen_random_uuid(), 'Superweld', 'superweld', NULL, '/brands/images-1.png') ON CONFLICT (slug) DO NOTHING;