INSERT INTO brands (brand_slug, brand_name) VALUES
('3d', '3D'),
('bathroom-products', 'Bathroom Products'),
('catering', 'Catering'),
('cleaning-supplies', 'Cleaning Supplies'),
('cornices', 'Cornices'),
('dromex', 'Dromex'),
('duraglove', 'Duraglove'),
('durawipe', 'Durawipe'),
('everest-safety', 'Everest Safety'),
('evergreen', 'Evergreen'),
('first-aid-safety', 'First Aid | Safety'),
('golden-hands', 'Golden Hands'),
('household', 'Household'),
('hygiene-protection', 'Hygiene Protection'),
('industrial-cleaning', 'Industrial Cleaning'),
('k-masks', 'K-Masks'),
('kiddies-corner', 'Kiddies Corner'),
('masks', 'Masks'),
('medical-disposal', 'Medical Disposal'),
('medical-ppe', 'Medical PPE'),
('nomex', 'Nomex'),
('ppe', 'PPE'),
('packaging', 'Packaging'),
('pinnacle', 'Pinnacle'),
('pioneer', 'Pioneer'),
('pride', 'Pride'),
('proflex', 'Proflex'),
('road-equipment', 'Road Equipment'),
('safety', 'Safety'),
('superweld', 'Superweld');